### ISSUE TITLE
issuing_jurisdiction check against stateOrProvinceName in DS certificate

### ISSUE THREAD

**Issue by warren-gallagher** [auth0-lab/mdl#26]
I believe that the existing check which matches the issuing_jurisdiction property agains the stateOrProvinceName in the DS certificate is not supposed to run if the issuer certificate does not include the stateOrProvinceName in the subject field.

From the spec:
If device retrieval is used, if the mDL reader retrieved the “issuing_jurisdiction” data element, it shall
verify that the value of that element matches the stateOrProvinceName element in the subject field
within the DS certificate (see Annex B). **This is only required if the stateOrProvinceName element is
present in the DS certificate**.

If server retrieval is used, if the mDL reader retrieved the “issuing_jurisdiction” data element, it shall
verify that the value of that element matches the stateOrProvinceName element in the subject field
within the JWS signer certificate (see Annex B). **This is only required if the stateOrProvinceName
element is present in the JWS signer certificate**.

**Comment by siacomuzzi** [comment]
good catch, thanks for reporting us!
