### ISSUE TITLE
Automatic adding of age_over_NN attributes

### ISSUE THREAD

**Issue by javereec** [auth0-lab/mdl#32]
I have observed that `age_over_NN` attributes are automatically added when `birthdate` is present. This works well for mDL, but might not be wanted when using mdoc in a more general way.

Do you want to keep this library mDL focussed as the name suggests or is the future direction to make it more generic?

**Comment by siacomuzzi** [comment]
Hi Jan,
Yeah, we are focusing on the ISO 18013-5 standard right now, but I guess we can add an extra check to include those `age_over_*` attributes only when specified namespace is `org.iso.18013.5.1`
