### ISSUE TITLE
Support of other DocTypes and namespaces

### ISSUE THREAD

**Issue by kkmanos** [auth0-lab/mdl#4]
Hello everyone,

In the framework of the MDoc implementation in wwWallet and the alignment with the EUDI ARF we noticed that in the library the org.iso.18013.5.1.mDL doc type is the only available option. Unfortunately this seems to be incompatible with the EUDI and ARF requirements which mandates a namespace and an attestation type of “eu.europa.ec.eudi.pid.<#increment>” for PIDs.

The library currently supports only the 'org.iso.18013.5.1.mDL' DocType, limiting its usability for developers who wish to implement solutions with custom DocTypes.

Adopting a more flexible approach to accommodate any DocType would be more than useful for anyone who is using this library as a core layer to implement solutions using the mDL specification ISO.18013-5.

**Comment by siacomuzzi** [comment]
Hi @kkmanos 
Could you please provide us with some examples and links about this?
Thank you in advance.

**Comment by dalebowie** [comment]
This might be as simple as removing the DocType restriction and instead allow any string to be specified as a DocType. Currently it is restricted to the specific mDL string:
```ts
export type DocType = 'org.iso.18013.5.1.mDL';
``` 
So maybe it could become this?
```
export type DocType = 'org.iso.18013.5.1.mDL' | string;
```

It appears the `addIssuerNameSpace` function already allows for arbitrary custom namespaces so that probably wouldn't have to change:
```ts
addIssuerNameSpace(namespace: 'org.iso.18013.5.1' | string, values: Record<string, any>): Document;
```

**Comment by siacomuzzi** [comment]
Yeah, that's correct.
My original question was out of curiosity, as the ISO standard currently only accepts `org.iso.18013.5.1.mDL`:

From `section 7.1 - mDL document type and namespace`:

> The document type for an mDL document shall be “org.iso.18013.5.1.mDL”.

**Comment by dalebowie** [comment]
I guess it comes down to whether you want this library to support only mDLs, or any arbitrary mdoc produced following the underlying standard. 

Here's a link to the [introduction of the PID for EUDI ARF](https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/1.4.0/annexes/annex-2/annex-2-high-level-requirements/#a233-topic-3-pid-rulebook). Then there's [this second document](https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/1.4.0/annexes/annex-3/annex-3.01-pid-rulebook/) with sections on [the doc type and namespace proposed](https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/1.4.0/annexes/annex-3/annex-3.01-pid-rulebook/#221-eu-wide-attestation-type-and-namespace-for-pid) and [notes specific to the mdoc encoding of it](https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/1.4.0/annexes/annex-3/annex-3.01-pid-rulebook/#242-isoiec-18013-5-compliant-encoding).

**Comment by dalebowie** [comment]
Thank you!

**Comment by kkmanos** [comment]
Hi everyone,

Thanks to the latest improvements in the library, we were able to successfully introduce the mDoc format in https://funke.wwwallet.org/ as part of the SPRIN-D Funke competition!

It will soon also be part of the core wwWallet software.

**Comment by siacomuzzi** [comment]
Nice!
Just FYI, this library was implemented in accordance with **ISO 18013-7 (draft date: 2023-08-02)**.
However, there is a more recent draft dated **2024-02-13** that we need to review to ensure the library is updated accordingly (for example, the structure of the session transcript was changed).
